### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by push-ebp0** [storycraft/node-kakao#114]
**Describe the bug**
await client.login(loginRes.result); -> TypeError: Cannot read property 'map' of undefined
```
(node:20160) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at TalkOpenLinkSession.getLatestLinkList (C:\Users\wjdtm\Desktop\4.0.0-alpha.4\node_modules\node-kakao\dist\talk\openlink\talk-openlink-session.js:36:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async OpenLinkService.getLatestLinkList (C:\Users\wjdtm\Desktop\4.0.0-alpha.4\node_modules\node-kakao\dist\talk\openlink\open-link-service.js:43:25)
    at async Function.initialize (C:\Users\wjdtm\Desktop\4.0.0-alpha.4\node_modules\node-kakao\dist\talk\openlink\open-link-service.js:83:13)
    at async TalkClient.login (C:\Users\wjdtm\Desktop\4.0.0-alpha.4\node_modules\node-kakao\dist\talk\client\index.js:106:13)
    at async run (C:\Users\wjdtm\Desktop\4.0.0-alpha.4\index.js:35:17)
```

getLatestLinkList() -> res.ols.map
(res = { status: 0, errMsg: null, ltk: 0 })

**To Reproduce**
4.0.0-alpha.4에서 로그인시 오류발생

**Comment by storycraft** [comment]
해당 계정의 오픈채팅 사용 가능 여부 또는 오픈 프로필 갯수를 같이 써주세요

**Comment by push-ebp0** [comment]
오픈채팅 사용 가능 = true
오픈 프로필 개수 = 0

**Comment by storycraft** [comment]
픽스가 포함된 다음 테스트 버전이 나왔기 때문에 닫습니다

**Comment by sonatina3** [comment]
4.0 정식에서 오픔 챗, 프로필 사용이 가능하지만 동일한 현상 발생됨.
