### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by ecclesia00** [storycraft/node-kakao#167]
**Describe the bug**
로그인시 오류발생.

**Error Log**
```
(node:5756) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of null
    at structToChannelInfo (bot\node_modules\node-kakao\dist\packet\struct\wrap\channel.js:20:55)
    at Object.structToOpenChannelInfo (bot\node_modules\node-kakao\dist\packet\struct\wrap\channel.js:57:16)
    at TalkOpenChannelSession.getLatestChannelInfo (bot\node_modules\node-kakao\dist\talk\openlink\talk-open-channel-session.js:56:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async TalkOpenChannel.getLatestChannelInfo (bot\node_modules\node-kakao\dist\talk\openlink\talk-open-channel.js:235:29)
    at async TalkOpenChannel.updateAll (bot\node_modules\node-kakao\dist\talk\openlink\talk-open-channel.js:343:29)
    at async TalkOpenChannelList.addOpenChannel (bot\node_modules\node-kakao\dist\talk\openlink\talk-open-channel-list.js:92:25)
    at async Promise.all (index 0)
    at async Function.initialize (bot\node_modules\node-kakao\dist\talk\openlink\talk-open-channel-list.js:210:13)
    at async Promise.all (index 1)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by storycraft** [comment]
오류가 나는 채팅방에 사람이 몇명 있나요?

**Comment by ecclesia00** [comment]
> 오류가 나는 채팅방에 사람이 몇명 있나요?

1명입니다.

**Comment by storycraft** [comment]
커밋 f09bbd90eaed438ec47553c2b4fd15ae3ffd9eee 서 픽스
