### ISSUE TITLE
오픈채팅방에서 프로필 수정할 경우 에러메시지 무한하게 발생함.

### ISSUE THREAD

**Issue by samknp** [storycraft/node-kakao#208]
**Describe the bug**
오픈채팅방에서 프로필 수정할 경우 에러메시지 무한하게 발생함.

**To Reproduce**
1. 오픈채팅방 입장
![image](https://user-images.githubusercontent.com/25787876/111892329-d2d8e500-8a3d-11eb-8a3d-f4d5a68654b6.png)
2. 프로필 변경
3. 에러가 무한정 발생

**Expected behavior**
프로필 변경되고 에러가 없어야 함

**Screenshots**
아래 에러가 무한정 발생합니다.
`
(node:23568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled 
with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 804)  
(node:23568) UnhandledPromiseRejectionWarning: Error: Tried to send data from closed socket
    at NodeSocket.write (C:\data\bot\Bot\node_modules\node-kakao\dist\network\socket\node-net-socket.js:63:23)
    at LocoSecureLayer.write (C:\data\bot\Bot\node_modules\node-kakao\dist\network\loco-secure-layer.js:110:33)
    at LocoPacketCodec.send (C:\data\bot\Bot\node_modules\node-kakao\dist\network\loco-packet-codec.js:49:33)
    at LocoPacketDispatcher.sendPacket (C:\data\bot\Bot\node_modules\node-kakao\dist\network\loco-packet-dispatcher.js:39:31)
    at DefaultLocoSession.request (C:\data\bot\Bot\node_modules\node-kakao\dist\network\request-session.js:46:48)
    at Timeout.pingHandler [as _onTimeout] (C:\data\bot\Bot\node_modules\node-kakao\dist\talk\client\index.js:185:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
`

**Comment by samknp** [comment]
추가적인 이슈 확인 후 리오픈 하겠습니다.
