### ISSUE TITLE
필요한 부분만 수정했는데.. SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ghost** [storycraft/node-kakao#272]
모듈은 npm i --save node-kakao로 다운받으 4.1.3인데요

```javascript
/*
 * Created on Sun Jan 31 2021
 *
 * Copyright (c) storycraft. Licensed under the MIT Licence.
 */

/*
 * Login using email, password using AuthApiClient.
 * Following this example will make automatic reply at text "안녕하세요" with mention.
 */

import { AuthApiClient, ChatBuilder, KnownChatType, MentionContent, ReplyContent, TalkClient } from 'node-kakao';

// Supply env variables or replace to value.
const DEVICE_UUID = process.env['y/gvs05hkvrXueOxNTNyunH1CAhqbKLu97P1Hh7HHCR5Eu/nU6IBRv4Z5C3c2WvRU7RtaUaJDh6suP4gLWO1xw=='];
const DEVICE_NAME = process.env['DESKTOP-SIDOR12'];

const EMAIL = process.env['메일@gmail.com'];
const PASSWORD = process.env['비번'];

const CLIENT = new TalkClient();

CLIENT.on('chat', (data, channel) => {
  const sender = data.getSenderInfo(channel);
  if (!sender) return;

  if (data.text === '안녕하세요') {
    // 답장 형식
    // 안녕하세요 @xxx
    channel.sendChat(
      new ChatBuilder()
      .append(new ReplyContent(data.chat))
      .text('안녕하세요 ')
      .append(new MentionContent(sender))
      .build(KnownChatType.REPLY));
    // 일반 텍스트
    // channel.sendChat('안녕하세요');
  }
});

async function main() {
  const api = await AuthApiClient.create(DEVICE_NAME, DEVICE_UUID);
  const loginRes = await api.login({
    email: EMAIL,
    password: PASSWORD,

    // This option force login even other devices are logon
    forced: true,
  });
  if (!loginRes.success) throw new Error(`Web login failed with status: ${loginRes.status}`);

  console.log(`Received access token: ${loginRes.result.accessToken}`);

  const res = await CLIENT.login(loginRes.result);
  if (!res.success) throw new Error(`Login failed with status: ${res.status}`);

  console.log('Login success');
}
main().then();
```

예시 코드 적고 필요한 부분만 수정했는데 왜 이럴까요...

```
PS D:\Project\Node JS\node-kakao> node index
(node:8328) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
D:\Project\Node JS\node-kakao\index.js:1
import { AuthApiClient, KnownAuthStatusCode } from 'node-kakao';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
PS D:\Project\Node JS\node-kakao>
```

**Comment by JellyBrick** [comment]
https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by dn1t** [comment]
package.json에 type: module 넣으시면 됩니다. 귀찮으면 그냥 require로 바꿔주셔도 되고요. 타입스크립트 코드라서 원래는 컴파일하면 require로 바뀝니다

**Comment by JellyBrick** [comment]
또한, 로그 및 코드는 코드 블럭을 활용해주세요.
`````
```
이 안에 코드 및 로그를 적어주세요.
```
`````
