### ISSUE TITLE
오픈채팅방 profile_changed 오류

### ISSUE THREAD

**Issue by MoonJR** [storycraft/node-kakao#273]
https://github.com/storycraft/node-kakao/blob/51960f48f23d05134b748cf873f09fdbc7362831/src/talk/openlink/talk-open-channel-handler.ts#L93

TalkClient 의 이벤스 수신중 profile_changed 수신시 오류발생. 

디버깅 해보면 프로파일 변경시 해당 부분에서 pfData.c 값이 undefined로 떨어져 eq 연산중 오류발생 => on.(error) 로 이벤트 전달됩니다.  

상태는 단채방에서 발생하였으며 간헐적이 아닌 지속적으로 발생하는것으로 판단됩니다.
(방장인상태, 일반 맴버인 상태 모두 발생되었습니다.)

하단 로그 첨부합니다~ 

```
TypeError: Cannot read property 'low' of undefined
    at Function.Long.fromValue (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/bson/lib/long.js:236:34)
    at Long.equals (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/bson/lib/long.js:416:26)
    at Long.eq (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/bson/lib/long.js:423:21)
    at TalkOpenChannelHandler._profileChangedHandler (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-handler.js:63:42)
    at TalkOpenChannelHandler.pushReceived (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-handler.js:141:26)
    at TalkOpenChannel.pushReceived (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/openlink/talk-open-channel.js:227:31)
    at TalkOpenChannelList.pushReceived (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-list.js:205:25)
    at TalkChannelList.pushReceived (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/talk-channel-list.js:85:24)
    at TalkClient.pushReceived (/Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/client/index.js:122:31)
    at /Users/jongrakmoon/dev/server/kakao_chatbot/node_modules/node-kakao/dist/talk/client/index.js:177:34

```

**Comment by storycraft** [comment]
테스트 결과 위와 같은 오류가 발생하지 않았습니다. 해당 오류가 특정 오픈 채팅방에서만 발생하나요? 만약 위 오류가 특정 채팅방에서만 발생한다면, 채팅방 유저 수 와 같은 채팅방의 간략한 정보를 제공해 주세요.

**Comment by MoonJR** [comment]
@storycraft 
여러가지 테스트를 진행해 보았는데 저의 경우 모든 TalkOpenChannel 에서 발생합니다. 
(1:1, 단체(인원 30), 방장, 매니저상태 등 여러가지 테스트 진행해보았습니다.)

버젼은 4.1.3 을 사용하고 있습니다.

**Comment by storycraft** [comment]
cafe78882f3e42e46860284f0396f15eca36a0bd 서 픽스
