### ISSUE TITLE
'TypeError: Cannot read property 'type' of undefined' in channel-manager.ts#L61

### ISSUE THREAD

**Issue by JellyBrick** [storycraft/node-kakao#36]
# **Describe the bug**
```
(node:31763) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at ChannelManager.channelFromChatData (/home/jellybrick/Dev/node-kakao/dist/talk/channel/channel-manager.js:42:26)
    at ChannelManager.fetchValue (/home/jellybrick/Dev/node-kakao/dist/talk/channel/channel-manager.js:38:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ChannelManager.get (/home/jellybrick/Dev/node-kakao/dist/store/store.js:57:19)
    at async TalkPacketHandler.onMessageRead (/home/jellybrick/Dev/node-kakao/dist/network/packet-handler.js:67:23)
```

# **To Reproduce**
1. TalkClient.login을 호출합니다.
2. 로그인이 완료되고, 메시지가 수신되면 오류가 발생합니다.

# **Expected behavior**
오류가 발생하지 않고 메시지가 잘 수신됨

**Comment by storycraft** [comment]
업데이트 이후 이슈가 확인 되지않아 닫습니다
