### ISSUE TITLE
HideChat() 시 Error: Session is not created 뜨며 가려지지 않는상황

### ISSUE THREAD

**Issue by generalxd** [storycraft/node-kakao#406]
**Describe the bug**
Ex) Reading CustomAttachment crashes client.

Hidechat() 을 사용할때

**Error: Session is not created
    at TalkClient.get session [as session] (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:77:23)
    at TalkClient.request (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:153:25)
    at Object.request (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:143:49)
    at TalkOpenChannelSession.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-session.js:169:45)
    at TalkOpenChannelDataSession.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-data-session.js:174:41)
    at TalkOpenChannel.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel.js:195:45)
    at /home/generalxd/kakao_project/project/ss/bot.js:295:41
    at step (/home/generalxd/kakao_project/project/ss/bot.js:33:23)
    at Object.next (/home/generalxd/kakao_project/project/ss/bot.js:14:53)
    at /home/generalxd/kakao_project/project/ss/bot.js:8:71**

에러가 뜨며 가려지지 않는현상

**To Reproduce**
Steps to reproduce the behavior.
Ex) 

1. 저녁 메시지가 많은 시간대에 폭탄메시지도 아닌 일반적인 글을 가리는데에 문제가 발생
2. 많은양의 패킷처리 또는 버퍼관련 부분의 문제로 보임
2. Hidechat() 으로 처리를하면
3. Error: Session is not created
    at TalkClient.get session [as session] (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:77:23)
    at TalkClient.request (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:153:25)
    at Object.request (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:143:49)
    at TalkOpenChannelSession.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-session.js:169:45)
    at TalkOpenChannelDataSession.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel-data-session.js:174:41)
    at TalkOpenChannel.hideChat (/usr/lib/node_modules/node-kakao/dist/talk/openlink/talk-open-channel.js:195:45)
    at /home/generalxd/kakao_project/project/ss/bot.js:295:41
    at step (/home/generalxd/kakao_project/project/ss/bot.js:33:23)
    at Object.next (/home/generalxd/kakao_project/project/ss/bot.js:14:53)
    at /home/generalxd/kakao_project/project/ss/bot.js:8:71
발생

**Expected behavior**
메시지가 가려지며 에러가 뜨면 안된다.

v3때는 똑같은 Condition에서 잘됐습니다.

**Screenshots**

**Comment by samknp** [comment]
session 이 종료된 상태에서 명령을 날리면 위와같은 에러가 나더라고요.

hideChat()이 문제가 아니라 파라미터가 잘못되었거나 연결이 종료된 상태였거나 등이 추측됩니다.

**Comment by generalxd** [comment]
> session 이 종료된 상태에서 명령을 날리면 위와같은 에러가 나더라고요.
> 
> hideChat()이 문제가 아니라 파라미터가 잘못되었거나 연결이 종료된 상태였거나 등이 추측됩니다.

파라미터 잘못된거없고 메시지 수신량이 많을때 세션이 끊기는걸로 추측됩니다.

V3에선 문제없었고 문제될만한 코드가없습니다.

정확히는 폭탄광고가 들어올떄 HideChat으로 요청을 계속보내다보니 세션이 끊기는거같습니다.

코드차원에서 TPS를 줘서 처리를 해봤으나

그래도 문제가생겨 노드카카오 모듈 자체의 오류로 생각들어 이슈올립니다.

**Comment by generalxd** [comment]
딜레이를 넣어 해결

**Comment by wiresharkkkk** [comment]
> 딜레이를 넣어 해결

혹시 딜레이를 어떻게 넣었는지 알 수 있을까요?
