### ISSUE TITLE
TypeError: Cannot read property 'chatId' of null

### ISSUE THREAD

**Issue by generalxd** [storycraft/node-kakao#432]
**Describe the bug**
Ex) Reading CustomAttachment crashes client.

**TypeError: Cannot read property 'chatId' of null
    at TalkChannelHandler._userLeftHandler (/usr/lib/node_modules/node-kakao/dist/talk/channel/talk-channel-handler.js:90:52)
    at TalkChannelHandler.pushReceived (/usr/lib/node_modules/node-kakao/dist/talk/channel/talk-channel-handler.js:144:26)
    at TalkNormalChannel.pushReceived (/usr/lib/node_modules/node-kakao/dist/talk/channel/talk-normal-channel.js:164:27)
    at TalkNormalChannelList.pushReceived (/usr/lib/node_modules/node-kakao/dist/talk/channel/talk-normal-channel-list.js:99:25)
    at TalkChannelList.pushReceived (/usr/lib/node_modules/node-kakao/dist/talk/talk-channel-list.js:84:26)
    at TalkClient.pushReceived (/usr/lib/node_modules/node-kakao/dist/talk/client/index.js:120:31)
    at /usr/lib/node_modules/node-kakao/dist/talk/client/index.js:176:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5)**

**To Reproduce**
Steps to reproduce the behavior.
Ex) 
1. 그냥 로그인되어있는 상태에서 메시지가 올때(누구 나가거나 강퇴당했을때로 예상됨)

         /usr/lib/node_modules/node-kakao/dist/talk/channel/talk-channel-handler.js
        _userLeftHandler(data, parentCtx)

        pushReceived(method, data, parentCtx)
        this._userLeftHandler(data, parentCtx);

에서 문제가 발생하는거 같습니다.

2. 해당 오류 발생

100% 재현 이슈
client.on("error", (error:unknown)=>{console.log(error)});
붙여줘야 나옴.

**Expected behavior**
문제 없이 ChannelId, ChatId 등 잘 잡아야함

**Screenshots**

**Comment by gabaekim** [comment]
저도 오래전부터 나오던 에러였습니다.

**Comment by generalxd** [comment]
해결완료
#37591cb
