### ISSUE TITLE
Session closed before response #316

### ISSUE THREAD

**Issue by kaan03** [storycraft/node-kakao#550]
봇 구동 후 몇 시간뒤에 위와같은 오류가 발생하면서 꺼졌습니다. 위 에러가 발생하였을때 꺼지지 않고 계속 구동하게 하려면 어떻게 해야하나요?

```
(node:8088) UnhandledPromiseRejectionWarning: Error: Session closed before response #316
    at LocoSession.request (C:\loco\node_modules\node-kakao\src\network\request-session.ts:157:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TalkChannelSession.sendChat (C:\loco\node_modules\node-kakao\src\talk\channel\talk-channel-session.ts:80:17)
    at TalkChannelDataSession.sendChat (C:\loco\node_modules\node-kakao\src\talk\channel\talk-channel-data-session.ts:36:17)
    at TalkOpenChannel.sendChat (C:\loco\node_modules\node-kakao\src\talk\openlink\talk-open-channel.ts:146:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by storycraft** [comment]
해당 오류는 라이브러리에서 버그가 아닌 잘못된 사용자 코드로 인한 오류입니다. 해당 부분 소스코드가 제공되지 않았기때문에 Invalid로 닫습니다.
