### ISSUE TITLE
ERROR 이벤트

### ISSUE THREAD

**Issue by low-lchf** [storycraft/node-kakao#552]
![Screenshot_20210730-184132_Termux](https://user-images.githubusercontent.com/70308414/127636565-b655d07c-76fa-4c6c-82f6-408ba9320dfd.jpg)
`

READY
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Error while processing packet#892660190 DECUNREAD: TypeError: Cannot read property 'Nickname' of null
    at MainInterface.responseReceived (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/loco/loco-interface.js:85:19)
    at LocoSecureSocket.dataReceived (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/loco-socket.js:76:27)
    at LocoPacketResolver._write (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/stream/loco-packet-resolver.js:37:29)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at LocoPacketResolver.Writable.write (internal/streams/writable.js:303:10)
    at LocoEncryptedTransformer.ondata (internal/streams/readable.js:719:22)
    at LocoEncryptedTransformer.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at LocoEncryptedTransformer.Readable.push (internal/streams/readable.js:223:10)
Emitted 'error' event on TalkClient instance at:
    at NetworkManager.onError (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/network-manager.js:160:21)
    at MainInterface.onError (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/loco/loco-interface.js:107:70)
    at LocoSecureSocket.onError (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/loco-socket.js:131:23)
    at LocoSecureSocket.onError (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/loco-secure-socket.js:69:15)
    at LocoSecureSocket.dataReceived (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/loco-socket.js:82:18)
    at LocoPacketResolver._write (/storage/emulated/0/Download/sellloco/vad/node_modules/node-kakao/dist/network/stream/loco-packet-resolver.js:37:29)
    [... lines matching original stack trace ...]
    at LocoEncryptedTransformer.emit (events.js:315:20)
$

갑자기 잘쓰다가 이렇게 오류 생기고 다시 설치해도 안되는데
패치된건가요

**Comment by storycraft** [comment]
v3은 지원되고있지 않습니다. 

이슈에 업로드하는 사진의 엑세스 토큰을 가려 주세요.
