### ISSUE TITLE
read ECONNABORTED 에러

### ISSUE THREAD

**Issue by tadashi74** [storycraft/node-kakao#591]
모바일에서 Termux 사용하여 봇을 돌리고 있습니다.
봇 구동후 일정 시간이 지나면 다음과 같은 에러가 발생합니다:
```
Client error: syscallError: read ECONNABORTED
(node:27514) UnhandledPromiseRejectionWarning: Error: read ECONNABORTED                                                         at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:27514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27514) UnhandledPromiseRejectionWarning: Error: read ECONNABORTED
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(node:27514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by storycraft** [comment]
해당 로그만으로는 오류가 왜 발생하는지 알기 어렵습니다. 버그리포트 템플릿을 사용해 주세요.
