### ISSUE TITLE
-4077 login error

### ISSUE THREAD

**Issue by ha1fstack** [storycraft/node-kakao#80]
**Describe the bug**
when login, the current error appears:
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on TalkClient instance at:
    at NetworkManager.onError (webpack:///./node_modules/node-kakao/dist/network/network-manager.js?:160:21)
    at MainInterface.onError (webpack:///./node_modules/node-kakao/dist/loco/loco-interface.js?:107:70)
    at LocoSecureSocket.onError (webpack:///./node_modules/node-kakao/dist/network/loco-socket.js?:131:23)
    at LocoSecureSocket.onError (webpack:///./node_modules/node-kakao/dist/network/loco-secure-socket.js?:69:15)
    at LocoSecureSocket.connectionError (webpack:///./node_modules/node-kakao/dist/network/loco-socket.js?:67:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

I've changed account / uuid / ip / pc but nothing works.
Actually the kakaotalk noti message for login is working (기기 로그인 알림:  ~에서 로그인했습니다.), but client fails.
Genuine PC client works as expected.

**To Reproduce**
attempt login

**Expected behavior**
normal login

**Screenshots**

**Comment by storycraft** [comment]
In some environments like Electron and Node-Webkit the packet serialization is buggy due to browserified modules or dependency's cross web, nodejs support logic. There is possibility the packet data became invalid and the server immediately disconnects the client.
